import { Todo} from "./todo"

export const TODOS: Todo [] = [
    {
        id: 1,
        title: "Todo 1",
        content: "Content todo 1",
        autor: "John Doe",
        isCompleted: false,
        createdAt: new Date(),
        completedAt: null,
    },
    {
        id: 2,
        title: "Todo 2",
        content: "Content todo 2",
        autor: "John Doe",
        isCompleted: true,
        createdAt: new Date(),
        completedAt: null,
    },
    {
        id: 1,
        title: "Todo 3",
        content: "Content todo 3",
        autor: "John Doe",
        isCompleted: false,
        createdAt: new Date(),
        completedAt: null,
    },
    {
        id: 4,
        title: "Todo 4",
        content: "Content todo 4",
        autor: "John Doe",
        isCompleted: true,
        createdAt: new Date(),
        completedAt: null,
    },
    {
        id: 5,
        title: "Todo 5",
        content: "Content todo 5",
        autor: "John Doe",
        isCompleted: false,
        createdAt: new Date(),
        completedAt: null,
    },
    {
        id: 6,
        title: "Todo 6",
        content: "Content todo 6",
        autor: "John Doe",
        isCompleted: true,
        createdAt: new Date(),
        completedAt: null,
    },
    {
        id: 7,
        title: "Todo 7",
        content: "Content todo 7",
        autor: "John Doe",
        isCompleted: false,
        createdAt: new Date(),
        completedAt: null,
    },
    {
        id: 8,
        title: "Todo 8",
        content: "Content todo 8",
        autor: "John Doe",
        isCompleted: true,
        createdAt: new Date(),
        completedAt: null,
    },
    {
        id: 9,
        title: "Todo 9",
        content: "Content todo 9",
        autor: "John Doe",
        isCompleted: false,
        createdAt: new Date(),
        completedAt: null,
    },
    {
        id: 10,
        title: "Todo 10",
        content: "Content todo 10",
        autor: "John Doe",
        isCompleted: true,
        createdAt: new Date(),
        completedAt: null,
    },
]